include:
  # Use the official GNOME release service component
  # This will handle the upload to download.gnome.org
  - component: "gitlab.gnome.org/GNOME/citemplates/release-service@master"
    inputs:
      job-stage: "release"
      dist-job-name: "build-release-tarball"

stages:
  - build
  - release
# The release service component's release job needs autotools to extract
# the version from configure.ac.
before_script:
  - dnf install -y autoconf automake autoconf-archive

.build-template:
  image: fedora:latest
  before_script:
    - dnf install -y autoconf automake autoconf-archive libtool make gettext-devel intltool pkgconfig xz bison flex
    - dnf install -y gcc gcc-c++
    - dnf install -y glib2-devel gtk3-devel vte291-devel gtksourceview4-devel
    - dnf install -y readline-devel ncurses-devel gmp-devel mpfr-devel

# Regular build to ensure things still compile on branches and merge requests
build:
  extends: .build-template
  stage: build
  script:
    - ./autogen.sh
    - make -j$(nproc)
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

# Special build that runs only on tags to create the release tarball
# Apparently, you need to create sha256sum, and you can apparently ignore
# documentation and just stuff the tarball you want into public-dist/
build-release-tarball:
  extends: .build-template
  stage: build
  script:
    - ./autogen.sh
    - make -j$(nproc)
    - make distcheck
    - mkdir -p "${CI_PROJECT_DIR}/public-dist/"
    - for n in *.xz ; do sha256sum "$n" > "${n}.sha256sum" ; done
    - cp genius-*.tar.xz genius-*.tar.xz.sha256sum "${CI_PROJECT_DIR}/public-dist/"
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: "always"
    paths:
      - "public-dist"
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "web"  # Allows manual start from "Build -> Pipelines -> Run pipeline"
      when: manual
    
